# Format and labels used aim to match those used by Ansible project
name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "Major Changes"
    labels:
      - "major" # c6476b
  - title: "Minor Changes"
    labels:
      - "feature" # 006b75
      - "minor"
  - title: "Bugfixes"
    labels:
      - "bug" # fbca04
      - "patch"
exclude-labels:
  - "skip-changelog"
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
      - "feature"
  patch:
    labels:
      - "patch"
      - "bug"
  default: patch
autolabeler:
  # converts commitlint/conventionalcommits format into labels that
  # release-drafter can use to produce the release notes.
  # https://github.com/conventional-changelog/commitlint#what-is-commitlint
  # External contributors do not have the ability to change labels but by
  # using conventional commits/pr titles the labels are automatially updated.
  - label: "skip-changelog"
    title:
      - "/(chore|ci|build|style|test)/i"
  - label: "bug"
    title:
      - "/(fix|revert|refactor|perf|docs)/i"
  - label: "feature"
    title:
      - "/feat/i"
  - label: "major"
    title:
      - "/!:/"
    body:
      - "/BREAKING CHANGE/"
template: |
  $CHANGES

  Kudos goes to: $CONTRIBUTORS
