name: setup
description: Runs steps to setup build environment

inputs:
  job_name:
    description: The name of the job
    default: preflight
runs:
  using: "composite"
  steps:
    - uses: jdx/mise-action@v4
      with:
        experimental: true
        # without specific version here will not upgrade old existing versions
        version: 2026.3.13
        reshim: true

    - name: Runner image version
      run: echo "IMAGE_OS_VERSION=${ImageOS}-${ImageVersion}-$(uname -m)" >> "$GITHUB_ENV"
      shell: bash

    - name: Enable caching for python
      # left out due to having their own caching: pnpm, node_modules, mise
      uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
      with:
        # we cache only wheels because http cache cannot be cleaned well
        path: |
          ${{ github.workspace }}/.cache/pip/wheels
          ${{ github.workspace }}/.cache/uv
        key: py-${{ env.IMAGE_OS_VERSION }}-${{ matrix.id }}-${{ hashFiles('uv.lock', '.python-version') }}

    - name: Enable caching for prek
      if: ${{ inputs.job_name == 'lint' || inputs.job_name == 'preflight' }}
      uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
      with:
        path: |
          ~/.cache/pre-commit/
          ~/.cache/prek/
          ~/.npm
        # ~/.npm is needed for the prek hooks using 'npx'
        key: pre-commit-4|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}

    - name: Get pnpm store directory
      id: pnpm-cache-dir-path
      run: echo "dir=$(pnpm store path)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Enable cache for pnpm
      uses: actions/cache@v5
      id: pnpm-cache # use this to check for `cache-hit` (`steps.pnpm-cache.outputs.cache-hit != 'true'`)
      with:
        path: ${{ steps.pnpm-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-

    - name: Enable caching for vscode resources
      if: "${{ contains(matrix.name, 'test') }}"
      # left out due to having their own caching: pnpm, node_modules, mise
      uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
      with:
        path: |
          .vscode-test/extensions
          .vscode-test/vscode-*
          out/ext
        key: ${{ env.IMAGE_OS_VERSION }}-${{ matrix.task-name }}-${{ hashFiles('package.json', 'pnpm-lock.yaml') }}
    # - name: Enable caching for podman-machine
    #   if: "contains(matrix.os, 'macos')"
    #   uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.0.0
    #   with:
    #     path: |
    #       ~/.local/share/containers
    #       ~/.config/containers
    #     key: ${{ runner.os }}-${{ matrix.task-name }}-${{ hashFiles('package.json', 'pnpm-lock.yaml', '.config/requirements.txt', '**/Taskfile.yml', 'tools/*.*') }}

    - name: Remove preinstalled pipx packages that can cause conflicts
      shell: bash
      run: |
        pipx list
        if [[ "${OSTYPE:-}" != darwin* && "${IS_WSL:-0}" != "1" ]]; then
          pipx uninstall --global ansible-core
        fi
