name: setup
description: Runs steps to setup build environment

inputs:
  job_name:
    description: The name of the job
    default: preflight
runs:
  using: "composite"
  steps:
    - name: Check mise setup
      id: check_mise
      run: |
        set -euo pipefail
        mise install
        mise reshim
        mise doctor
        mise env
      shell: bash
      continue-on-error: true

    - name: Debug
      run: |
        echo "steps.check_mise.outcome: ${{ steps.check_mise.outcome }}"
        echo "steps.check_mise.conclusion: ${{ steps.check_mise.conclusion }}"
      shell: bash

    - uses: jdx/mise-action@146a28175021df8ca24f8ee1828cc2a60f980bd5 # v3.5.1
      if: steps.check_mise.outcome != 'success'
      with:
        experimental: true
        # without specific version here will not upgrade old existing versions
        version: 2025.12.1
        # https://github.com/jdx/mise-action/issues/165
        mise_dir: ~/.local/bin
        reshim: true

    - name: Corepack enable
      run: corepack enable
      shell: bash

    - name: Runner image version
      run: echo "IMAGE_OS_VERSION=${ImageOS}-${ImageVersion}" >> "$GITHUB_ENV"
      shell: bash

    - name: Enable caching for python
      # left out due to having their own caching: yarn, node_modules, mise
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        # we cache only wheels because http cache cannot be cleaned well
        path: |
          ~/.cache/pip/wheels
          ~/.cache/uv
        key: py-${{ env.IMAGE_OS_VERSION }}-${{ matrix.id }}-${{ hashFiles('uv.lock', '.python-version') }}

    - name: Enable caching for pre-commit
      if: ${{ inputs.job_name == 'lint' || inputs.job_name == 'preflight' }}
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: ~/.cache/pre-commit/
        key: pre-commit-4|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}
