name: setup
description: Runs steps to setup build environment

inputs:
  job_name:
    description: The name of the job
    default: preflight
runs:
  using: "composite"
  steps:
    - uses: jdx/mise-action@6d1e696aa24c1aa1bcc1adea0212707c71ab78a8 # v3.6.1
      with:
        experimental: true
        # without specific version here will not upgrade old existing versions
        version: 2026.2.13
        reshim: true

    - name: Corepack enable
      run: corepack enable
      shell: bash

    - name: Runner image version
      run: echo "IMAGE_OS_VERSION=${ImageOS}-${ImageVersion}-$(uname -m)" >> "$GITHUB_ENV"
      shell: bash

    - name: Enable caching for python
      # left out due to having their own caching: yarn, node_modules, mise
      uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
      with:
        # we cache only wheels because http cache cannot be cleaned well
        path: |
          ~/.cache/pip/wheels
          ~/.cache/uv
        key: py-${{ env.IMAGE_OS_VERSION }}-${{ matrix.id }}-${{ hashFiles('uv.lock', '.python-version') }}

    - name: Enable caching for prek
      if: ${{ inputs.job_name == 'lint' || inputs.job_name == 'preflight' }}
      uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
      with:
        path: |
          ~/.cache/pre-commit/
          ~/.cache/prek/
        key: pre-commit-4|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Enable cache for yarn
      uses: actions/cache@v5
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Enable caching for vscode resources
      if: "${{ contains(matrix.name, 'test') }}"
      # left out due to having their own caching: yarn, node_modules, mise
      uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
      with:
        path: |
          .vscode-test/extensions
          .vscode-test/vscode-*
          out/ext
        key: ${{ env.IMAGE_OS_VERSION }}-${{ matrix.task-name }}-${{ hashFiles('package.json', 'yarn.lock') }}
    # - name: Enable caching for podman-machine
    #   if: "contains(matrix.os, 'macos')"
    #   uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.0.0
    #   with:
    #     path: |
    #       ~/.local/share/containers
    #       ~/.config/containers
    #     key: ${{ runner.os }}-${{ matrix.task-name }}-${{ hashFiles('package.json', 'yarn.lock', '.config/requirements.txt', '**/Taskfile.yml', 'tools/*.*') }}

    - name: Remove preinstalled pipx packages that can cause conflicts
      shell: bash
      run: |
        pipx list
        if [[ "${OSTYPE:-}" != darwin* && "${IS_WSL:-0}" != "1" ]]; then
          pipx uninstall --global ansible-core
        fi
