# https://github.com/yarnpkg/yarn/issues/3368
ignores:
  - "@ansible/ansible-mcp-server"
  - "@ansible/ansible-language-server"
  - "@types/vscode-webview" # provides VSCodeAPI
  - "@types/vscode"  # determined by (package.json).engines.vscode
  - "@vscode/test-electron" # used by @vscode/test-cli
  - "@vscode/vsce"
  - c8 # used in unit-tests script
  - cypress-multi-reporters
  - depcheck
  - electron
  - eslint-formatter-gha
  - eslint-formatter-unix
  - mocha-junit-reporter
  - mocha-multi-reporters
  - npm-check-updates
  - ovsx
  - rimraf
  - start-server-and-test
  - tmp
  - ts-loader
  - ts-node
  - vscode
  - webpack-cli
  - yarn-audit-fix
