ignores:
  - "@ansible/ansible-language-server"
  - "@types/vscode-webview" # provides VSCodeAPI
  - "@vscode/vsce"
  - depcheck
  - mochawesome
  - mochawesome-report-generator
  - ovsx
  - rimraf
  - start-server-and-test
  - tmp
  - ts-loader
  - vscode
  - webpack-cli
  - yarn-audit-fix
