# $schema: https://json.schemastore.org/eslintrc
env:
  commonjs: true
  # Check https://kangax.github.io/compat-table/es2016plus/ and correlated
  # with minimal version of node that we target.
  es2021: true
  node: true
extends:
  - plugin:@typescript-eslint/recommended
  - prettier
ignorePatterns:
  - out
  - media
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2021
  sourceType: module
plugins:
  - "@typescript-eslint"
  - prettier
  - eslint-plugin-tsdoc
rules:
  eqeqeq:
    - error
    - smart
  prefer-template: error
  prettier/prettier: error
  tsdoc/syntax: error
