# Markdown Lint Rules
# https://github.com/mivok/markdownlint/blob/master/docs/RULES.md

MD014: false # Dollar signs used before commands without showing output
MD013: false # Line length (we should only use reformatting tool for this, like prettier)
MD046: false # raises false possibilities with docs admonitions
MD060: false # Table column style - tables are valid even if not perfectly aligned
