# Markdown Lint Rules
# https://github.com/mivok/markdownlint/blob/master/docs/RULES.md

MD014: false # Dollar signs used before commands without showing output (we use mkdocs-material to add the real output)
MD013: false # Line length (we should only use reformatting tool for this, like prettier)
MD046: false # raises false possibilities with mkdocs-material admonitions https://squidfunk.github.io/mkdocs-material/reference/admonitions/
