# Used only by 'unit' tests
# 'e2e' is configured via .vscode-test.mjs
# 'ui' is configured via test/ui/.mocharc.js
extension: ["ts"]
require: ts-node/register
package: "./package.json"
timeout: 30003 # default is 2000
# most UI tests are >22s due to our current wait times and we do not want
# red slow marker to distract us until we sort that part yet. Red is expected
# to appear on unexpected long tests, not on an expected duration.
slow: 25000
