---
all: true
check-coverage: true
# https://github.com/istanbuljs/nyc
# Exclude files from elsewhere and avoid random error like
# https://github.com/istanbuljs/nyc/issues/847
include:
  - src/**/*.ts
lines: 2.7
recursive: true
report-dir: out/coverage/unit
reporter:
  - lcov
  - text
require:
  - ts-node/register
skip-full: true
temp-dir: out/out/coverage/unit/.nyc_output
