tabWidth: 2
useTabs: false
overrides:
  - files:
      - "*.yaml"
      - "*.yml"
    options:
      singleQuote: false
  - files:
      - "*.md"
    options:
      proseWrap: always
      printWidth: 80
semi: true
singleQuote: true
