# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html
# for details

---

# Required
version: 2

mkdocs:
  fail_on_warning: true
  configuration: mkdocs.yml

# Optionally build your docs in additional formats
# such as PDF and ePub
formats: []

submodules:
  include: all  # []
  exclude: []
  recursive: true

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
  apt_packages:
    - curl
    - file
    - git
    - libgbm-dev
    - libonig-dev
    - libssh-dev
    - python3-pip
    - python3-venv
    - qemu-user-static
    - x11-xserver-utils
    - xvfb
  jobs:
    build:
      html:
        - >
          UV_PROJECT_ENVIRONMENT=$READTHEDOCS_VIRTUALENV_PATH
          PATH=~/.local/bin:$PATH
          CI=1
          ~/.local/bin/mise exec -- task docs
    create_environment:
      - curl https://mise.run | sh
      - ~/.local/bin/mise settings experimental=true
      - ~/.local/bin/mise settings python.compile=false
      - ~/.local/bin/mise settings python.uv_venv_auto=true
      - ~/.local/bin/mise trust
      - ~/.local/bin/mise install -v
      - ~/.local/bin/mise exec -- uv venv "${READTHEDOCS_VIRTUALENV_PATH}"
      - ~/.local/bin/mise exec -- task --version

    install:
      # Custom docs dependencies installation, based on uv.lock
      - >
        VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH
        UV_CACHE_DIR=$READTHEDOCS_VIRTUALENV_PATH/../../uv_cache
        ~/.local/bin/mise exec -- uv sync --active --locked
