# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html
# for details

---

# Required
version: 2

mkdocs:
  fail_on_warning: true
  configuration: mkdocs.yml

# Optionally build your docs in additional formats
# such as PDF and ePub
formats: []

submodules:
  include: all  # []
  exclude: []
  recursive: true

build:
  os: ubuntu-24.04
  tools:
    python: >-  # PyYAML parses it as float `3.1` it it's not an explicit string
      3.12
  jobs:
    install:
      - asdf plugin add task
      - asdf install task
      - pip install -r .config/requirements.in -c .config/constraints.txt
