# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html
# for details

---

# Required
version: 2

mkdocs:
  fail_on_warning: true

# Optionally build your docs in additional formats
# such as PDF and ePub
formats: []

submodules:
  include: all  # []
  exclude: []
  recursive: true

build:
  os: ubuntu-22.04
  tools:
    python: >-  # PyYAML parses it as float `3.1` it it's not an explicit string
      3.10

# Optionally set the version of Python and requirements required
# to build docs
python:
  install:
    # We also defined PIP_CONSTRAINTS=.config/requirements.txt on readthedocs config
    - requirements: .config/requirements.in
