compressionLevel: mixed

enableGlobalCache: true

enableTelemetry: 0

nodeLinker: node-modules

packageExtensions:
  cypress-multi-reporters@*:
    dependencies:
      mocha: "*"
  mocha-junit-reporter@*:
    dependencies:
      mocha: "*"
  mocha-multi-reporters@*:
    dependencies:
      mocha: "*"
plugins:
  - checksum: 113fae572c391623e3032d2be1c3eac64ca8d00cfb7fa62a4dab433b87bb66864a577acad63c0a16895869930a41587f409d9de2de69fd1ad539dee6ea9c6bdf
    path: .yarn/plugins/plugin-list.cjs
    spec: "https://github.com/arendjr/yarn-plugin-list/releases/latest/download/yarn-plugin-list.js"

supportedArchitectures:
  cpu:
    - x64
    - arm64
  os:
    - linux
    - darwin
    - win32

yarnPath: .yarn/releases/yarn-4.12.0.cjs
logFilters:
  - code: YN0060
    level: error # forces yarn install to fail to prevent regressions when updating dependencies
  # Remove next ones once addressed:
  - code: YN0060
    pattern: "eslint is listed by your project with version"
    level: warning
  - code: YN0060
    pattern: "vite is listed by your project with version"
    level: warning
