compressionLevel: mixed

enableGlobalCache: true

nodeLinker: node-modules

supportedArchitectures:
  cpu:
    - x64
    - arm64
  os:
    - linux
    - darwin
    - win32

yarnPath: .yarn/releases/yarn-3.6.4.cjs
