# To update yarn version, run: yarn set version latest"
enableGlobalCache: true

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

supportedArchitectures:
  cpu:
    - x64
    - arm64
  os:
    - linux
    - darwin
    - win32

yarnPath: .yarn/releases/yarn-3.6.0.cjs
