codecov:
  require_ci_to_pass: false
  notify:
    after_n_builds: 3 # effectively number of uploads: linux, macos, wsl
    wait_for_ci: false
comment: false
coverage:
  status:
    patch: false
    project: true
