# cspell: ignore multicriteria
# sonar does not support cobertura coverage xml format, only lcov.info
# Disable insecure os command execution inside tests
sonar.debug=true
sonar.log.level.app=DEBUG
sonar.organization=ansible
sonar.projectKey=ansible_vscode-ansible
sonar.sources=src/,packages/common/src/,packages/language-server/src/,packages/lightspeed/src/,packages/mcp-server/src/,packages/services/src/,packages/ui/src/,packages/lightspeed/webviews/src/
sonar.tests=test/,packages/language-server/test/,packages/lightspeed/test/,packages/mcp-server/test/,packages/services/test/,packages/ui/test/
sonar.verbose=true
