---
# see https://taskfile.dev/#/
version: "3"
output: group
env: &env
  FORCE_COLOR: "true"
  PRE_COMMIT_COLOR: always
  # basically the same thing from .envrc file:
  VIRTUAL_ENV: # "{{.VIRTUAL_ENV}}"
    sh: echo "${VIRTUAL_ENV:-out/venvs/${HOSTNAME:-localhost}}"
vars:
  HOSTNAME:
    sh: echo ${HOSTNAME:-localhost}
  VERSION:
    sh: node -p "require('./package.json').version"
tasks:
  default:
    desc: Run most commands
    deps:
      - setup
      - lint
      - package
    cmds:
      - echo {{.TASK}}
      - echo Done {{.VERSION}}!
  devel:
    desc: Updates the language server to latest from @main and run all tests
    deps:
      - setup
    cmds:
      - tools/dirty.sh
      # If we call `task devel -- <path>` we will link that path, otherwise
      # we will just update ansible-language-server to @main.
      - "{{if .CLI_ARGS}}yarn link {{.CLI_ARGS}}{{else}}yarn up '@ansible/ansible-language-server@https://github.com/ansible/ansible-language-server#main'{{end}}"
      - >
        bash -c 'git diff --quiet --exit-code || {
        git add package.json yarn.lock &&
        echo "Update ansible-language-server" |
        git commit --file -
        ;}'
      - tools/dirty.sh
      - task: test
      - echo "Tests passed, you can now run "task pr" to create a pull request."
  clean:
    desc: Clean up all files that not tracked by git
    cmds:
      - git clean -dxf
  setup:
    desc: Install dependencies
    env:
      # used inside test-setup.sh
      OS: "{{OS}}"
      ARCH: "{{ARCH}}"
    cmds:
      - bash ./tools/test-setup.sh
    sources:
      - tools/test-setup.sh
      - package.json
      - yarn.lock
      - Taskfile.yml
    generates:
      - node_modules
      - out/log/manifest.yml
    run: once
  build:
    desc: Build the project
    deps:
      - setup
    cmds:
      # Workaround for https://github.com/redhat-developer/vscode-extension-tester/pull/460#issuecomment-1166315428
      # - cd node_modules/vscode-extension-tester && npm update vsce
      - yarn run compile
    sources:
      - Taskfile.yml
      - node_modules/**/*
      - package.json
      - src/
      - tsconfig.json
      - webpack.config.js
      - yarn.lock.json
  code:
    env:
      # https://github.com/microsoft/vscode/issues/82524#issuecomment-1150315756
      NODE_OPTIONS: "--no-deprecation"
    desc: Forced install of extension in your code instance
    deps:
      - package
    cmds:
      - code --force --install-extension *.vsix
  deps:
    desc: Update dependencies
    deps:
      - setup
    cmds:
      - $VIRTUAL_ENV/bin/python -m piptools compile -q --no-header --no-annotate .config/requirements.txt --output-file .config/requirements.txt
      - $VIRTUAL_ENV/bin/python -m pre_commit autoupdate
      # bumps some developments dependencies
      - yarn upgrade-interactive
      # running install after upgrade is needed in order to update the lock file
      - yarn install
    interactive: true
  lint:
    desc: Lint the project
    deps:
      - setup
    cmds:
      - $VIRTUAL_ENV/bin/python -m pre_commit run -a
      - tools/dirty.sh
    silent: true
    sources:
      - "*.*"
      - .config
      - .github
      - .vscode
      - doc
      - examples
      - images
      - src
      - syntaxes
      - test
      - tools
  test:
    desc: Run all tests
    cmds:
      - task: test-ui
      - task: test-e2e
      - tools/dirty.sh
    interactive: true
  test-e2e:
    desc: Run e2e tests
    deps:
      - package
    cmds:
      - >
        source "${VIRTUAL_ENV}/bin/activate" &&
        yarn run test-e2e
    interactive: true
  test-ui:
    desc: Run UI tests
    deps:
      - package
    cmds:
      - >
        source "${VIRTUAL_ENV}/bin/activate" &&
        yarn run test-ui-current
      - >
        source "${VIRTUAL_ENV}/bin/activate" &&
        yarn run test-ui-oldest
    interactive: true
  package:
    desc: Package extension
    deps:
      - build
    sources:
      - CHANGELOG.md
      - README.md
      - package*.json
      - out/
    generates:
      - "*.vsix"
    cmds:
      - rm -f *.vsix
      - yarn run webpack
      # --pre-release not supported until we do VS Code >=1.63
      # --no-dependencies and --no-yarn needed due to https://github.com/microsoft/vscode-vsce/issues/439
      - npx vsce package --no-dependencies --no-git-tag-version --no-update-package-json {{.VERSION}}-next-1
      # Using zipinfo instead of `npx vsce ls` due to https://github.com/microsoft/vscode-vsce/issues/517
      - zipinfo -1 *.vsix
      - tools/dirty.sh
    silent: true
  pr:
    desc: Opens a pull request using gh
    deps:
      - lint
    cmds:
      - gh pr create
    interactive: true
  release:
    desc: Create a new release (used by CI)
    deps:
      - setup
    cmds:
      - ./tools/release.sh
    interactive: true
