---
# see https://taskfile.dev/#/
version: "3"
includes:
  als:
    taskfile: ./packages/ansible-language-server
    dir: ./packages/ansible-language-server
output: prefixed # do not use "group" due to impact on CI
env: &env
  FORCE_COLOR: "true"
  PRE_COMMIT_COLOR: always
  # basically the same thing from .envrc file:
  VIRTUAL_ENV: # "{{.VIRTUAL_ENV}}"
    sh: echo "${VIRTUAL_ENV:-${PWD}/out/venvs/{{.HOSTNAME}}}"
vars:
  HOSTNAME:
    sh: echo ${HOSTNAME:-${HOST:-$(hostname)}}
  XVFB:
    # prefix to add to allow execution of test in headless machines (CI)
    sh: bash -c 'if [[ "$OSTYPE" == "linux-gnu"* ]] && command -v xvfb-run >/dev/null; then echo "$(command -v xvfb-run) --auto-servernum -e out/log/xvfb.log"; fi'
tasks:
  default:
    vars:
      VERSION:
        sh: node -p "require('./package.json').version"
    desc: Run most commands
    deps:
      - install
      - lint
      - package
    cmds:
      - echo {{.TASK}}
      - echo Done {{.VERSION}}!
  clean:
    desc: Clean up all files that not tracked by git
    cmds:
      - git clean -dxf
  setup:
    desc: Install dependencies
    env:
      # used inside test-setup.sh
      OS: "{{OS}}"
      ARCH: "{{ARCH}}"
    cmds:
      - python3 ./tools/precheck.py
      - bash ./tools/test-setup.sh
    sources:
      - tools/test-setup.sh
    generates:
      - out/log/manifest-{{.HOSTNAME}}.yml
    run: once
    interactive: true
  install:
    deps:
      - setup
    cmds:
      - yarn install
    sources:
      - "**/package.json"
      - yarn.lock
      - node_modules/**/*
    interactive: true
  build:
    desc: Build the project
    deps:
      - install
    cmds:
      # Workaround for https://github.com/redhat-developer/vscode-extension-tester/pull/460#issuecomment-1166315428
      # - cd node_modules/vscode-extension-tester && npm update vsce
      - yarn run clean
      - yarn run als-compile
      - yarn run compile
      - npx tsc -p ./
    sources:
      - Taskfile.yml
      - node_modules/**/*
      - package.json
      - src/**/*
      - test/**/*
      - tsconfig.json
      - webpack.config.ts
      - yarn.lock.json
  code:
    env:
      # https://github.com/microsoft/vscode/issues/82524#issuecomment-1150315756
      NODE_OPTIONS: "--no-deprecation"
    desc: Forced install of extension in your code instance
    deps:
      - package
    cmds:
      - code --force --install-extension *.vsix
  deps:
    desc: Update dependencies
    deps:
      - install
    cmds:
      # upgrade yarn itself
      - yarn set version latest
      # bumps some developments dependencies
      - yarn upgrade-interactive
      # running install after upgrade is needed in order to update the lock file
      - yarn install
      # check deps
      - yarn dlx depcheck
      - $VIRTUAL_ENV/bin/python3 ./tools/precheck.py
      - $VIRTUAL_ENV/bin/python3 -m pre_commit autoupdate
    interactive: true
  lint:
    desc: Lint the project
    deps:
      - install
    cmds:
      - $VIRTUAL_ENV/bin/python3 ./tools/precheck.py
      - $VIRTUAL_ENV/bin/python3 -m pre_commit run -a
      - tools/dirty.sh
    silent: true
    sources:
      - "*.*"
      - .config
      - .github
      - .vscode
      - doc
      - examples
      - images
      - src
      - syntaxes
      - test
      - tools
  test:
    desc: Run all tests
    deps:
      - setup
      - package
    cmds:
      - task: unit
      #- task: test-ui
      #- task: test-ui-old
      - task: test-e2e
      - tools/dirty.sh
    interactive: true
  test-e2e:
    desc: Run e2e tests
    deps:
      - package
    cmds:
      - $VIRTUAL_ENV/bin/python3 --version
      - '{{.XVFB}} bash -c ''source "${VIRTUAL_ENV}/bin/activate" && yarn run _coverage-all'''
    interactive: true
  test-ui:
    desc: Run UI tests
    deps:
      - package
    cmds:
      - $VIRTUAL_ENV/bin/python3 --version
      - bash -c 'source "${VIRTUAL_ENV}/bin/activate" && yarn run test-ui-current'
    interactive: true
  test-ui-old:
    desc: Run UI tests (oldest vscode)
    deps:
      - package
    cmds:
      - $VIRTUAL_ENV/bin/python3 --version
      - bash -c 'source "${VIRTUAL_ENV}/bin/activate" && yarn run test-ui-oldest'
    interactive: true
  unit:
    desc: Run unit tests with coverage report
    cmds:
      - npm run unit-tests
    interactive: true
  package:
    vars:
      VERSION:
        sh: node -p "require('./package.json').version"
    desc: Package extension
    deps:
      - build
      # while not a real dependency, we want to build both all the time:
      - als:package
    sources:
      - CHANGELOG.md
      - README.md
      - package*.json
      - out/
      - webpack.config.ts
      - Taskfile.yml
    generates:
      - "*.vsix"
    cmds:
      - rm -f *.vsix
      - yarn run webpack
      # --pre-release not supported until we do VS Code >=1.63
      # --no-dependencies and --no-yarn needed due to https://github.com/microsoft/vscode-vsce/issues/439
      - yarn run vsce package --pre-release --no-dependencies --no-git-tag-version --no-update-package-json {{.VERSION}}
      # Using zipinfo instead of `npx vsce ls` due to https://github.com/microsoft/vscode-vsce/issues/517
      - zipinfo -1 *.vsix
      - tools/dirty.sh
      - ls -la *.vsix
    silent: true
  pr:
    desc: Opens a pull request using gh
    deps:
      - lint
    cmds:
      - gh pr create
    interactive: true
  release:
    desc: Create a new release (used by CI)
    deps:
      - install
    cmds:
      - ./tools/release.sh
    interactive: true
