# see https://taskfile.dev/#/
version: "3"
output: group
vars:
  VENV_PATH: '{{default ".venv" (env "VIRTUAL_ENV")}}'
  VENV_PYTHON: '{{if (eq OS "windows")}}{{.VENV_PATH}}/Scripts/python.exe{{else}}{{.VENV_PATH}}/bin/python{{end}}'
  VERSION:
    sh: node -p "require('./package.json').version"
tasks:
  default:
    desc: Run most commands
    deps:
      - setup
      - lint
      - package
    cmds:
      - echo {{.TASK}}
      - echo Done {{.VERSION}}!
  setup:
    desc: Install dependencies
    cmds:
      - bash ./tools/test-setup.sh
      - npm ci
    env:
      VENV_PATH: '{{.VENV_PATH}}'
    sources:
      - node_modules/**/*
      - tools/test-setup.sh
      - package.json
      - package-lock.json
      - Taskfile.yml
    generates:
      - .venv
      - node_modules
  build:
    desc: Build the project
    deps:
      - setup
    cmds:
      - npm run compile && sleep 1
    sources:
      - node_modules/**/*
      - package-lock.json
      - package.json
      - src/
      - tsconfig.json
      - webpack.config.js
      - Taskfile.yml
  code:
    desc: Forced install of extension in your code instance
    deps:
      - package
    cmds:
      - npm run package && code --force --install-extension *.vsix
  deps:
    desc: Update dependencies
    deps:
      - setup
    cmds:
      - "{{.VENV_PYTHON}} -m pre_commit autoupdate"
      # bumps some developments dependencies
      - npx ncu -u --dep dev
      # running install after ncu is needed in order to update the lock file
      - npm install
  lint:
    desc: Lint the project
    deps:
      - setup
    env:
      PRE_COMMIT_COLOR: always
    cmds:
      - "{{.VENV_PYTHON}} -m pre_commit run -a"
    silent: true
    sources:
      - "*.*"
      - .config
      - .github
      - .vscode
      - doc
      - examples
      - images
      - src
      - syntaxes
      - test
      - tools
  test:
    desc: Run all tests
    deps:
      - test-ui
      - test-e2e
    interactive: true
  test-e2e:
    desc: Run e2e tests
    deps:
      - package
    cmds:
      - >
        source "${VENV_PATH:-.venv}/bin/activate" &&
        npm run test-e2e
    interactive: true
  test-ui:
    desc: Run UI tests
    deps:
      - build
    cmds:
      - >
        source "${VENV_PATH:-.venv}/bin/activate" &&
        npm run test-ui-current
      - >
        source "${VENV_PATH:-.venv}/bin/activate" &&
        npm run test-ui-oldest
    interactive: true
  package:
    desc: Package extension
    deps:
      - build
    sources:
      - CHANGELOG.md
      - README.md
      - package*.json
      - out/
    generates:
      - "*.vsix"
    cmds:
      - rm -f *.vsix
      - npm run webpack
      # --pre-release not supported until we do VS Code >=1.63
      - npx vsce package --no-git-tag-version --no-update-package-json {{.VERSION}}-next-1
      - npx vsce ls
    silent: true
  pr:
    desc: Opens a pull request using gh
    deps:
      - lint
    cmds:
      - gh pr create
    interactive: true
