import { execFileSync } from "node:child_process";
import {
  existsSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { afterEach, beforeAll, describe, expect, it, vi } from "vitest";
import { run } from "@src/cli.js";

const pkgRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const pkg = JSON.parse(readFileSync(resolve(pkgRoot, "package.json"), "utf8"));

/**
 * Run the built CLI and return stdout/stderr/status without throwing on
 * non-zero exits.
 *
 * @param args - CLI arguments after the binary path.
 * @returns Captured process result.
 */
function runBuiltCli(args: string[]): {
  status: number | null;
  stdout: string;
  stderr: string;
} {
  try {
    const stdout = execFileSync(process.execPath, [binPath, ...args], {
      timeout: 30_000,
      encoding: "utf8",
      env: { ...process.env, NODE_NO_WARNINGS: "1" },
    });
    return { status: 0, stdout, stderr: "" };
  } catch (err: unknown) {
    const e = err as {
      status?: number;
      stdout?: string | Buffer;
      stderr?: string | Buffer;
    };
    return {
      status: e.status ?? 1,
      stdout: String(e.stdout ?? ""),
      stderr: String(e.stderr ?? ""),
    };
  }
}

const binPath = resolve(pkgRoot, pkg.bin as string);

describe("CLI entry point (built bin)", () => {
  let tempDir: string | undefined;

  beforeAll(() => {
    // Built CJS entry embeds PACKAGE_VERSION via tsdown define.
    if (!existsSync(binPath)) {
      execFileSync("pnpm", ["run", "compile"], {
        cwd: pkgRoot,
        stdio: "pipe",
        timeout: 120_000,
        env: { ...process.env, NODE_NO_WARNINGS: "1" },
      });
    }
  });

  afterEach(() => {
    if (tempDir !== undefined) {
      rmSync(tempDir, { recursive: true, force: true });
      tempDir = undefined;
    }
  });

  it("bin field points to a file that exists after build", () => {
    expect(
      existsSync(binPath),
      `bin target "${pkg.bin}" not found at ${binPath}`,
    ).toBe(true);
  });

  it("prints package version for --version", () => {
    const result = runBuiltCli(["--version"]);
    expect(result.status).toBe(0);
    expect(result.stdout.trim()).toBe(pkg.version);
  });

  it("rejects --generate-docs without an output path", () => {
    const result = runBuiltCli(["--generate-docs"]);
    expect(result.status).toBe(1);
    expect(result.stderr).toContain(
      "Usage: ansible-language-server --generate-docs <output-md-file>",
    );
  });

  it("rejects --generate-docs when the next token is another flag", () => {
    // Use a flag other than --version: --version is handled first in cli.ts.
    const result = runBuiltCli(["--generate-docs", "--help"]);
    expect(result.status).toBe(1);
    expect(result.stderr).toContain(
      "Usage: ansible-language-server --generate-docs <output-md-file>",
    );
  });

  it("writes settings docs for --generate-docs <file>", () => {
    tempDir = mkdtempSync(join(tmpdir(), "als-cli-docs-"));
    const outPath = join(tempDir, "settings.md");

    const result = runBuiltCli(["--generate-docs", outPath]);
    expect(result.status).toBe(0);
    expect(existsSync(outPath)).toBe(true);

    const content = readFileSync(outPath, "utf8");
    expect(content).toContain("Do not edit this file directly");
    expect(content).toContain("# Language Server Settings");
    expect(content).toMatch(/ansible\.\w+/);
  });

  it("exits with an error when --generate-docs cannot write the file", () => {
    tempDir = mkdtempSync(join(tmpdir(), "als-cli-docs-fail-"));
    const blocker = join(tempDir, "not-a-dir");
    writeFileSync(blocker, "x");
    const outPath = join(blocker, "settings.md");

    const result = runBuiltCli(["--generate-docs", outPath]);
    expect(result.status).toBe(1);
    expect(result.stderr.length).toBeGreaterThan(0);
  });
});

describe("CLI run() (source)", () => {
  let tempDir: string | undefined;

  afterEach(() => {
    vi.restoreAllMocks();
    if (tempDir !== undefined) {
      rmSync(tempDir, { recursive: true, force: true });
      tempDir = undefined;
    }
  });

  it("returns 0 and prints version for --version", async () => {
    const log = vi.spyOn(console, "log").mockImplementation(() => undefined);
    await expect(run(["--version"])).resolves.toBe(0);
    expect(log).toHaveBeenCalledWith(pkg.version);
  });

  it("returns 1 and prints usage when --generate-docs has no path", async () => {
    const err = vi.spyOn(console, "error").mockImplementation(() => undefined);
    await expect(run(["--generate-docs"])).resolves.toBe(1);
    expect(err).toHaveBeenCalledWith(
      "Usage: ansible-language-server --generate-docs <output-md-file>",
    );
  });

  it("writes settings docs and returns 0", async () => {
    tempDir = mkdtempSync(join(tmpdir(), "als-cli-run-docs-"));
    const outPath = join(tempDir, "settings.md");
    await expect(run(["--generate-docs", outPath])).resolves.toBe(0);
    const content = readFileSync(outPath, "utf8");
    expect(content).toContain("# Language Server Settings");
  });
});
