import { mkdtempSync, readFileSync, unlinkSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { generateSettingsDocs } from "@src/settings-doc-generator";

describe("generateSettingsDocs", () => {
  let outPath: string | undefined;

  afterEach(() => {
    if (outPath !== undefined) {
      try {
        unlinkSync(outPath);
      } catch {
        // ignore missing file
      }
      outPath = undefined;
    }
  });

  it("writes markdown with generator banner and ansible settings", () => {
    const dir = mkdtempSync(join(tmpdir(), "als-settings-doc-"));
    outPath = join(dir, "settings.md");
    generateSettingsDocs(outPath);
    const content = readFileSync(outPath, "utf8");
    expect(content).toContain("Do not edit this file directly");
    expect(content).toContain("task docs");
    expect(content).toContain("# Language Server Settings");
    expect(content).toMatch(/ansible\.\w+/);
  });
});
