---
name: ðŸ› Bug report
description: Create a report to help us improve
labels: bug

body:
  - type: markdown
    attributes:
      value: >
        **Thanks for taking the time to fill out this bug report!**

        âš 
        Please, verify first that your issue is not [already reported][issues].

        ðŸ›ˆ
        **Tip:** If you are seeking community support, or want to ask a question,
        please consider [starting a discussion][discussions].

        [issues]: ../search?q=is%3Aissue&type=issues
        [discussions]: ../discussions

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: A clear and concise description of what the bug is.
      placeholder: >-
        TLDR: When I do X, VS Code does/shows Y instead of Z.

        To elaborate [...]

        ðŸ›ˆ
        **Tip:** You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: true

  - type: input
    id: extension-version
    attributes:
      label: Extension version
    validations:
      required: true

  - type: input
    id: vscode-version
    attributes:
      label: VS Code version
    validations:
      required: true

  - type: textarea
    id: ansible-version
    attributes:
      label: Ansible Version
      description: >-
        Paste verbatim output from `ansible --version` below. **This will be
        automatically formatted into code, so no need for backticks.**
      render: shell
      placeholder: |
        $ ansible --version
        ansible [core 2.11.1] 
          config file = ~/.ansible.cfg
          configured module search path = ['~/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
          ansible python module location = ~/venv/ansible4/lib/python3.6/site-packages/ansible
          ansible collection location = ~/.ansible/collections:/usr/share/ansible/collections
          executable location = ~/venv/ansible4/bin/ansible
          python version = 3.6.9 (default, Jul 17 2020, 12:50:27) [GCC 8.4.0]
          jinja version = 3.0.1
          libyaml = True
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: OS / Environment
      description: >-
        Provide all relevant information, including OS, remote extension used (underlying OS too),
        `ansible-lint` version etc.
      placeholder: Windows 10, WSL (Ubuntu 18.04), ansible-lint 5.0.12
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: >-
        Please copy and paste any relevant log output (from `Output > Ansible
        Server`). **This will be automatically formatted into code, so no need
        for backticks.**
      render: shell
