---
name: 🐛 Bug report
description: Create a report to help us improve
labels:
  - bug
  - new

body:
  - type: markdown
    attributes:
      value: >-
        **Thanks for taking the time to fill out this bug report!**


        ⚠ Please, verify first that your issue is not [already reported][issues].


        🛈 **Tip:** If you are seeking community support, or want to ask a
        question, please consider [starting a discussion][discussions].


        []: # (cspell: disable-next-line)
        [issues]: ../search?q=is%3Aissue&type=issues

        [discussions]: ../discussions

  - type: markdown
    attributes:
      value: >
        _Hold on, wait a second, **🛑 STOP!**_


        🙏 We need you to confirm something first before proceeding with
        filling out this form.

        💡 Long story short, it is important to verify that you actually
        use the `redhat.ansible` extension for a given file.

        <details>
          <summary>
            📖 Long story long.
          </summary>

          <p>
            We noticed, that some people miss out on what extension is
            being used to handle certain files. In some cases, VS Code's
            auto-detection selects a different extension for a file you
            are looking at. In case, it doesn't choose the
            <code>Ansible</code> language for such a file,
            <code>redhat.ansible</code> will even not get
            initialized and you'll actually be getting errors from other
            extensions. <i>This may be confusing and misleading</i>.
          </p>

          <p>
            When VS Code auto-detects a file language, it saves it for
            future reference and it won't re-assign a different
            extension to it automatically. Only the extension that
            processes that language will be in control of working with
            that file. It is technically impossible within the VS Code
            ecosystem for <code>redhat.ansible</code> to "steal" that
            control from any other extension. Most often this happens
            with pre-existing extensions that provide support for YAML.
          </p>

          <p>
            But you can select it manually by clicking on the current
            language in your editor's status bar and choosing
            <code>Ansible</code> from the selection. With this, VS Code
            will remember the language for that specific file. You may
            need to repeat this for other files that got a wrong language.
          </p>
        </details>


        🙏 Look at your VS Code status bar and verify that it has
        the `Ansible` language selected for the files that are part of
        your Ansible project.


        <details>
          <summary>
            ❗ This is what the status bar should look like.
          </summary>


          ![❗ VS Code Ansible language selected
          ](https://user-images.githubusercontent.com/578543/141507613-ef7ec8eb-f75b-4f6e-8580-750678768b90.png)
        </details>

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: >-
        A clear and concise description of what the bug is.

        🛈 **Tip:** You can attach images or log files by clicking this area to
        highlight it and then dragging files in.
      placeholder: |
        TLDR: When I do X, VS Code does/shows Y instead of Z.

        To elaborate [...]
    validations:
      required: true

  - type: input
    id: extension-version
    attributes:
      label: Extension version
    validations:
      required: true

  - type: input
    id: vscode-version
    attributes:
      label: VS Code version
    validations:
      required: true

  - type: textarea
    id: ansible-version
    attributes:
      label: Ansible Version
      description: >-
        Paste verbatim output from `ansible --version` below.

        **This will be automatically formatted into code, so no need for
        backticks.**
      render: shell
      placeholder: |
        $ ansible --version
        ansible [core 2.11.1]
          config file = ~/.ansible.cfg
          configured module search path = ['~/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
          ansible python module location = ~/venv/ansible4/lib/python3.6/site-packages/ansible
          ansible collection location = ~/.ansible/collections:/usr/share/ansible/collections
          executable location = ~/venv/ansible4/bin/ansible
          python version = 3.6.9 (default, Jul 17 2020, 12:50:27) [GCC 8.4.0]
          jinja version = 3.0.1
          libyaml = True
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: OS / Environment
      description: >-
        Provide all relevant information, including OS, remote extension used
        (underlying OS too), `ansible-lint` version etc.
      placeholder: Windows 10, WSL (Ubuntu 18.04), ansible-lint 5.0.12
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: >-
        Please copy and paste any relevant log output (from `Output > Ansible
        Server`).

        **This will be automatically formatted into code, so no need for
        backticks.**
      render: shell
