---
name: 💡 Feature request
description: Suggest an idea for this project
labels:
  - feature
  - new

body:
  - type: markdown
    attributes:
      value: >-
        **Thanks for taking the time to fill out this feature request!**


        ⚠ Please, verify first that the feature you want is not [already requested][issues].


        🛈 **Tip:** If you are seeking community support, or want to ask a
        question, please consider [starting a discussion][discussions].

        []: # (cspell: disable-next-line)
        [issues]: ../search?q=is%3Aissue&type=issues

        [discussions]: ../discussions

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: >-
        Is your feature request related to a problem? Please describe.

        🛈 **Tip:** You can attach images or log files by clicking this area to
        highlight it and then dragging files in.
      placeholder: |
        A clear and concise description of what the problem is.
        Example: I'm always frustrated when [...]

    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Solution
      description: Describe the solution you'd like.
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Describe alternatives you've considered.
      placeholder: >-
        A clear and concise description of any alternative solutions or features
        you've considered.

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request.
