export const taskKeywords = new Set([
  'action',
  'any_errors_fatal',
  'args',
  'async',
  'become',
  'become_exe',
  'become_flags',
  'become_method',
  'become_user',
  'changed_when',
  'check_mode',
  'collections',
  'connection',
  'debugger',
  'delay',
  'delegate_facts',
  'delegate_to',
  'diff',
  'environment',
  'failed_when',
  'ignore_errors',
  'ignore_unreachable',
  'local_action',
  'loop',
  'loop_control',
  'module_defaults',
  'name',
  'no_log',
  'notify',
  'poll',
  'port',
  'register',
  'remote_user',
  'retries',
  'run_once',
  'tags',
  'throttle',
  'timeout',
  'until',
  'vars',
  'when',
]);

export function isTaskKeyword(value: string): boolean {
  return taskKeywords.has(value) || value.startsWith('with_');
}
