# https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/enabling-and-disabling-dependabot-version-updates
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "skip-changelog"
  - package-ecosystem: docker
    # We use this file to load the last known good versions of creator-ee and
    # constraints.
    directory: .config/
    schedule:
      interval: daily
    labels:
      - dependencies
      - skip-changelog
