codecov:
  notify:
    after_n_builds: 8  # the number of individual jobs in the test matrix
    wait_for_ci: true
  require_ci_to_pass: true
comment: false
coverage:
  status:
    patch: false
    project:
      default:
        threshold: 0.5%
