---
# see https://taskfile.dev/#/
version: "3"
env:
  # basically the same thing from .env file:
  # Avoid undesired extra hints from docker when pulling images
  DOCKER_CLI_HINTS: "false"
vars:
  EE_VERSION:
    sh: ./tools/get-image-version
  VIRTUAL_ENV:
    sh: echo "${HOME}/.local/share/virtualenvs/vsa"
includes:
  base:
    taskfile: ../../Taskfile.base.yml
    internal: true
    flatten: true
tasks:
  default:
    dir: "{{ .TASKFILE_DIR }}"
    desc: Run most commands
    env:
      VERSION:
        sh: node -e "const fs = require('fs'); const pkg = JSON.parse(fs.readFileSync('./package.json', 'utf8')); console.log(pkg.version);"
    sources:
      - ../../vitest.config.ts
      - package.json
      - pyproject.toml
      - src/**/*.*
      - test/**/*.*
      - tsconfig.json
      - webpack.config.js
      - yarn.lock
    generates:
      - "*.tgz"
    deps:
      - package
    cmds:
      - task: test
      - echo Done ansible-language-server {{.VERSION}}!
  build:
    dir: "{{ .TASKFILE_DIR }}"
    desc: Build the project
    deps:
      - setup
    cmds:
      - yarn run compile
    sources:
      - package-lock.json
      - package.json
      - src/**/*.*
      - test/**/*.*
      - tsconfig.json
      - webpack.config.js
  test:
    desc: Run all tests using node (same version as vscode), will skip @ee tests if both SKIP_PODMAN=1 and SKIP_DOCKER=1.
    dir: "{{ .TASKFILE_DIR }}"
    interactive: true
    deps:
      - build
    sources:
      - ../../pyproject.toml
      - ../../uv.lock
      - ../../vitest.config.ts
      - ../../yarn.lock
      - package.json
      - src/**/*.*
      - test/**/*.*
      - tsconfig.json
      - webpack.config.js
    generates:
      - ../../out/coverage/als/cobertura-coverage.xml # codecov.io
      - ../../out/coverage/als/coverage-final.json # IDE plugins
      - ../../out/coverage/als/lcov.info # sonar
      - ../../out/junit/als-test-results.xml
    cmds:
      - bash -c ". {{.VIRTUAL_ENV}}/bin/activate && command -v ansible-lint && npm run test"
  test-with-ee:
    dir: "{{ .TASKFILE_DIR }}"
    desc: Run only ee tests
    deps:
      - build
    cmds:
      - >
        . {{.VIRTUAL_ENV}}/bin/activate &&
        bash -c 'npm run test-with-ee'
    interactive: true
  test-without-ee:
    desc: Run only non-ee tests
    dir: "{{ .TASKFILE_DIR }}"
    deps:
      - build
    cmds:
      - bash -c '. {{.VIRTUAL_ENV}}/bin/activate && npm run test-without-ee'
    interactive: true
  package:
    desc: Package extension
    dir: "{{ .TASKFILE_DIR }}"
    sources:
      - ../../docs/als/changelog.md
      - README.md
      - package.json
      - out/server/
    generates:
      - "*.tgz"
    deps:
      - build
    cmds:
      - rm -f {{ .TASKFILE_DIR }}/*.tgz
      - yarn pack --out '{{ .TASKFILE_DIR }}/%s-%v.tgz'
    silent: false
  release:
    desc: Create a new release (used by CI)
    dir: "{{ .TASKFILE_DIR }}"
    cmds:
      - ./tools/release.sh
    interactive: true
