---
# see https://taskfile.dev/#/
version: "3"
includes:
  shared:
    taskfile: ../../.config/Taskfile_shared.yml
    dir: ../..
    internal: true
env: &env
  # basically the same thing from .envrc file:
  # Avoid undesired extra hints from docker when pulling images
  DOCKER_CLI_HINTS: "false"
vars:
  EE_VERSION:
    sh: ./tools/get-image-version
  VIRTUAL_ENV:
    sh: echo "${HOME}/.local/share/virtualenvs/vsa"
tasks:
  default:
    dir: "{{ .TASKFILE_DIR }}"
    desc: Run most commands
    env:
      VERSION:
        sh: node -p "require('./package.json').version"
    cmds:
      - task: package
      - task: test
      - echo Done ansible-language-server {{.VERSION}}!
  build:
    dir: "{{ .TASKFILE_DIR }}"
    desc: Build the project
    cmds:
      - task: shared:install
      - yarn run compile
    sources:
      - package-lock.json
      - package.json
      - src/**/*.*
      - test/**/*.*
      - tsconfig.json
      - webpack.config.js
  deps:
    dir: "{{ .TASKFILE_DIR }}"
    desc: Update dependencies
    cmds:
      - npm install -g npm@latest
      # - installs tools from .tool-versions
      - asdf install
      - "{{.VIRTUAL_ENV}}/bin/python3 -m pre_commit autoupdate"
      - npm outdated
      # bumps some developments dependencies
      - npx ncu -u --dep dev
      # running install after ncu is needed in order to update the lock file
      - npm install
  .test:
    # Keep the desc empty to hide entry when listing
    # desc: Run all tests
    dir: "{{ .TASKFILE_DIR }}"
    cmds:
      - task: build
      - bash -c "source {{.VIRTUAL_ENV}}/bin/activate && command -v ansible-lint && npm run test"
    interactive: true
  test:
    desc: Run all tests using node (same version as vscode), will skip @ee tests if both SKIP_PODMAN=1 and SKIP_DOCKER=1.
    dir: "{{ .TASKFILE_DIR }}"
    cmds:
      # - bash -c 'asdf local nodejs latest:18 latest:$(asdf nodejs resolve lts)'
      - task: .test
  test-node-lts:
    dir: "{{ .TASKFILE_DIR }}"
    desc: Run all tests using node-lts (future)
    cmds:
      - task: shared:install
      # switch to last nodejs version listed in .tool-versions
      - git clean -dxf
      - bash -c "cd ../.. && asdf local nodejs $(cat ../../.tool-versions|grep nodejs|awk '{print $NF}')"
      - node --version
      - task: .test
      # restore implicit node version
      - defer: git checkout HEAD .tool-versions
      - defer: git clean -dxf
  test-with-ee:
    dir: "{{ .TASKFILE_DIR }}"
    desc: Run only ee tests
    cmds:
      - task: build
      - >
        source {{.VIRTUAL_ENV}}/bin/activate &&
        bash -c 'npm run test-with-ee'
    interactive: true
  test-without-ee:
    desc: Run only non-ee tests
    dir: "{{ .TASKFILE_DIR }}"
    cmds:
      - task: build
      - >
        source {{.VIRTUAL_ENV}}/bin/activate &&
        bash -c 'npm run test-without-ee'
    interactive: true
  package:
    desc: Package extension
    dir: "{{ .TASKFILE_DIR }}"
    sources:
      - ../../docs/als/changelog.md
      - README.md
      - package*.json
      - out/**/*.*
    generates:
      - "*.tgz"
    cmds:
      - task: build
      - rm -f {{ .TASKFILE_DIR }}/*.tgz
      - yarn pack --out '{{ .TASKFILE_DIR }}/%s-%v.tgz'
    silent: false
  release:
    desc: Create a new release (used by CI)
    dir: "{{ .TASKFILE_DIR }}"
    cmds:
      - ./tools/release.sh
    interactive: true
