---
# see https://taskfile.dev/#/
env:
  # basically the same thing from .env file:
  # Avoid undesired extra hints from docker when pulling images
  DOCKER_CLI_HINTS: "false"
vars:
  PROJECT: ansible-language-server
  EE_VERSION:
    sh: node ../../tools/get-image-version.mts
  VIRTUAL_ENV:
    sh: echo "${HOME}/.local/share/virtualenvs/vsa"
includes:
  base:
    taskfile: ../../Taskfile.base.yml
    # internal: true
    flatten: true
tasks:
  default:
    dir: "{{ .TASKFILE_DIR }}"
    desc: Run most commands
    deps:
      - package
    cmds:
      - task: test
      - echo Done {{.PROJECT}} {{.VERSION}}!
  build:
    dir: "{{ .TASKFILE_DIR }}"
    desc: Build the project
    deps:
      - setup
    cmds:
      - pnpm run compile
      - pnpm exec ansible-language-server --generate-docs ../../docs/als/settings.md
    generates:
      - lib/**/*.*
    sources:
      - ../../pnpm-lock.yaml
      - package.json
      - src/**/*.*
      - test/**/*.*
      - tsconfig.json
      - tsup.config.ts
      - ../../tsconfig*.json
  test:
    desc: Run all tests using node (same version as vscode), will skip @ee tests if both SKIP_PODMAN=1 and SKIP_DOCKER=1.
    dir: "{{ .TASKFILE_DIR }}"
    interactive: true
    env:
      TMP: "{{ .TASKFILE_DIR }}/../../out/als/tmp"
      TMPDIR: "{{ .TASKFILE_DIR }}/../../out/als/tmp"
    deps:
      - build
    sources:
      - ../../pyproject.toml
      - ../../uv.lock
      - ../../vitest.config.ts
      - ../../pnpm-lock.yaml
      - package.json
      - src/**/*.*
      - test/**/*.*
      - tsconfig.json
    generates:
      - ../../out/coverage/unit/cobertura-coverage.xml # codecov.io
      - ../../out/coverage/unit/lcov.info # sonar
      - ../../out/junit/unit-test-results.xml
    cmds:
      - bash -c ". {{.VIRTUAL_ENV}}/bin/activate && command -v ansible-lint && pnpm run test"
  test-with-ee:
    dir: '{{ .TASKFILE_DIR }}'
    desc: Run only ee tests
    deps:
      - build
    cmds:
      - |
        . {{.VIRTUAL_ENV}}/bin/activate && bash -c 'pnpm run test-with-ee'
    interactive: true
  test-without-ee:
    desc: Run only non-ee tests
    dir: '{{ .TASKFILE_DIR }}'
    deps:
      - build
    cmds:
      - bash -c '. {{.VIRTUAL_ENV}}/bin/activate && pnpm run test-without-ee'
    interactive: true
  package:
    desc: Package {{ .PROJECT }}
    deps:
      - build
    dir: "{{ .TASKFILE_DIR }}"
    sources:
      - ../../docs/als/changelog.md
      - README.md
      - package*.json
      - tsconfig.json
      - tsup.config.ts
    generates:
      - dist/**/*
      - '{{ .GIT_ROOT }}/out/ansible-{{ .PROJECT }}-{{ .VERSION }}.tgz'
    cmds:
      - rm -f {{ .GIT_ROOT }}/out/ansible-{{ .PROJECT }}-*.tgz
      - npm version {{ .VERSION }} --no-git-tag-version
      - npm pack --silent --pack-destination '{{ .GIT_ROOT }}/out'
      - defer: npm version 0.0.0 --no-git-tag-version
    silent: false
  release:
    desc: Create a new release (used by CI)
    dir: '{{ .TASKFILE_DIR }}'
    cmds:
      - ./tools/release.sh
    interactive: true
version: "3"
