name: prek
description: Run prek hooks (lint)

outputs:
  context:
    description: Extracted commit context from conventional commit message
    value: ${{ steps.extract_context.outputs.context }}
  tasks:
    description: JSON list of known task names and aliases
    value: ${{ steps.extract_context.outputs.tasks }}

runs:
  using: "composite"
  steps:
    # needed by our prek system hooks like toml
    - name: Install uv (cache)
      uses: astral-sh/setup-uv@v8.2.0

    # needed by our prek systems hooks like biome
    - name: Install node (cache)
      uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
      with:
        node-version: "24"

    - name: Install pnpm # needs node 24
      uses: pnpm/action-setup@v6
      with:
        cache: true
        run_install: |
          - recursive: true
            args: [--frozen-lockfile]

    - name: Debug
      shell: bash
      run: |
        which -a pnpm
        pnpm --version

    - name: Run prek
      uses: j178/prek-action@v2
      # ideally prek should run in under 30s, but we keep a hard limit of 3
      # minutes to count for slower hooks and uncached data. If a hook is
      # slower, even occasionally it should be moved outside and included in
      # another build step, like 'build' or 'package'.
      # timeout-minutes: 3
      with:
        # show-verbose-logs: true
        # we want to run in verbose to report speed of each hook
        extra-args: "--all-files -v"
        install-only: false
        prek-version: ">=0.3.8"
