FROM quay.io/ansible/creator-ee:v24.2.0 as DEFAULT_EE
# This file is updated by dependabot and used to determine not only which
# version of creator-ee we are supposed to use for testing execution
# environments but also to dynamically retrieve the same set of constraints
# for testing outside execution environments.
#
# Do not rename this file to Containerfile due to
# https://github.com/dependabot/dependabot-core/issues/6067
