[env]
_.file = { path = ".env", tools = true }
_.path = ["./node_modules/.bin"]

# Do not use other hooks than preinstall or postinstall because they will
# not work without 'mise activate' command, something that we do not use on CI.
[hooks]

[settings]
# Needs to be enabled for hooks to work
experimental = true
idiomatic_version_file_enable_tools = ["python"]
lockfile = true
http_retries = 5

[tools]
node = "24.17"
python = { version = "3.13", os = ["linux", "macos"] }
task = "latest"  # >=3.45 but mise does not support minimal condition
uv = "latest"
pnpm = "11.8.0"
