#!/usr/bin/env python
import glob
import os
import sys
import subprocess

for src in glob.glob("syntaxes/ansible/*.plist"):
    dst = os.path.splitext(os.path.basename(src))[0]
    cmd = [sys.executable, "syntaxes/plist2xml.py", src, f"syntaxes/ansible/generated/{dst}"]
    print(f"Running: {' '.join(cmd)}")
    subprocess.run(
        cmd,
        check=True
        )
