apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
    annotations:
        build.appstudio.openshift.io/repo: https://github.com/ansible/vscode-ansible?rev={{revision}}
        build.appstudio.redhat.com/commit_sha: "{{revision}}"
        build.appstudio.redhat.com/pull_request_number: "{{pull_request_number}}"
        build.appstudio.redhat.com/target_branch: "{{target_branch}}"
        pipelinesascode.tekton.dev/cancel-in-progress: "true"
        pipelinesascode.tekton.dev/max-keep-runs: "3"
        pipelinesascode.tekton.dev/on-cel-expression:
            event == "pull_request" && target_branch
            == "main"
    creationTimestamp: null
    labels:
        appstudio.openshift.io/application: vscode-ansible
        appstudio.openshift.io/component: vscode-ansible
        pipelines.appstudio.openshift.io/type: build
    name: vscode-ansible-on-pull-request
    namespace: ansible-lightspeed-tenant
spec:
    params:
        - name: git-url
          value: "{{source_url}}"
        - name: revision
          value: "{{revision}}"
        - name: output-image
          value: quay.io/redhat-user-workloads/ansible-lightspeed-tenant/vscode-ansible:on-pr-{{revision}}
        - name: image-expires-after
          value: 5d
        - name: dockerfile
          value: ./vscode-ansible.Containerfile
    pipelineRef:
        name: vscode-ansible-build-pipeline
    taskRunTemplate:
        serviceAccountName: build-pipeline-vscode-ansible
    workspaces:
        - name: workspace
          volumeClaimTemplate:
              metadata:
                  creationTimestamp: null
              spec:
                  accessModes:
                      - ReadWriteOnce
                  resources:
                      requests:
                          storage: 1Gi
              status: {}
        - name: git-auth
          secret:
              secretName: "{{ git_auth_secret }}"
status: {}
