#!/usr/bin/env bash
version="latest"

if [[ -f ".config/Containerfile" ]]; then
  while IFS= read -r line; do
    if [[ $line == FROM* ]]; then
      version="${line#*:}"
      version="${version%% *}"  # Strip anything after a space
      break
    fi
  done < ".config/Containerfile"
fi

printf "%s" "$version"
