---
# see https://taskfile.dev/#/
version: "3"
env:
  # basically the same thing from .env file:
  # Avoid undesired extra hints from docker when pulling images
  DOCKER_CLI_HINTS: "false"
includes:
  base:
    taskfile: ../../Taskfile.base.yml
    internal: true
    flatten: true

tasks:
  default:
    dir: "{{ .TASKFILE_DIR }}"
    desc: Run most commands
    env:
      VERSION:
        sh: node -p "require('./package.json').version"
    cmds:
      - task: package
      - task: test
      - echo Done ansible-mcp-server {{.VERSION}}!
  build:
    dir: "{{ .TASKFILE_DIR }}"
    desc: Build the project
    deps:
      - setup
    cmds:
      - npm run compile
    generates:
      - out/server/**/*.*
    sources:
      - package-lock.json
      - package.json
      - "{src,test}/**/*.*"
      - tsconfig.json
      - vitest.config.ts
      - exclude: "**/*-artifact-*.json"
      - exclude: ansible-navigator.log
  test:
    desc: Run all tests and coverage report
    deps:
      - build
    dir: "{{ .TASKFILE_DIR }}"
    status:
      - test -f ../../out/junit/mcp/.passed
    sources:
      - package.json
      - "{src,test}/**/*.*"
      - tsconfig.json
      - vitest.config.ts
      - exclude: "**/*-artifact-*.json"
      - exclude: ansible-navigator.log
    cmds:
      - rm -f ../../out/junit/mcp/.passed
      - npm run test:coverage
      - touch ../../out/junit/mcp/.passed
    interactive: true
  test-watch:
    desc: Run tests in watch mode
    dir: "{{ .TASKFILE_DIR }}"
    cmds:
      - npm run test:watch
    interactive: true
  package:
    desc: Package MCP server
    deps:
      - build
    dir: "{{ .TASKFILE_DIR }}"
    sources:
      - README.md
      - package*.json
      - src/**/*.*
      - tsconfig.json
    generates:
      - "*.tgz"
    cmds:
      - rm -f {{ .TASKFILE_DIR }}/*.tgz
      - yarn pack --out '{{ .TASKFILE_DIR }}/%s-%v.tgz'
    silent: false
  clean:
    desc: Clean build artifacts
    dir: "{{ .TASKFILE_DIR }}"
    cmds:
      - rm -rf out/server
      - rm -rf node_modules/.cache
