---
# see https://taskfile.dev/#/
env:
  # basically the same thing from .env file:
  # Avoid undesired extra hints from docker when pulling images
  DOCKER_CLI_HINTS: "false"
vars:
  PROJECT: ansible-mcp-server
  VIRTUAL_ENV:
    sh: echo "${HOME}/.local/share/virtualenvs/vsa"
includes:
  base:
    taskfile: ../../Taskfile.base.yml
    # internal: true
    flatten: true
tasks:
  default:
    dir: "{{ .TASKFILE_DIR }}"
    desc: Run most commands
    deps:
      - package
    cmds:
      - task: test
      - echo Done {{.PROJECT}} {{.VERSION}}!
  build:
    dir: "{{ .TASKFILE_DIR }}"
    desc: Build the project
    deps:
      - setup
    cmds:
      - pnpm run compile
    generates:
      - lib/**/*.*
    sources:
      - ../../pnpm-lock.yaml
      - package.json
      - src/**/*.*
      - test/**/*.*
      - tsconfig.json
      - tsup.config.ts
      - ../../tsconfig*.json
      - exclude: "**/*-artifact-*.json"
  test:
    desc: Run all tests and coverage report
    dir: "{{ .TASKFILE_DIR }}"
    interactive: true
    deps:
      - build
    sources:
      - ../../vitest.config.ts
      - package.json
      - src/**/*.*
      - test/**/*.*
      - tsconfig.json
      - exclude: "**/*-artifact-*.json"
    generates:
      - ../../out/coverage/unit/cobertura-coverage.xml # codecov.io
      - ../../out/coverage/unit/lcov.info # sonar
      - ../../out/junit/unit-test-results.xml
    cmds:
      - pnpm run test
  test-watch:
    desc: Run tests in watch mode
    dir: "{{ .TASKFILE_DIR }}"
    cmds:
      - pnpm run test:watch
    interactive: true
  package:
    desc: Package {{ .PROJECT }}
    deps:
      - build
    dir: "{{ .TASKFILE_DIR }}"
    sources:
      - README.md
      - package*.json
      - tsconfig.json
      - tsup.config.ts
    generates:
      - dist/**/*
      - '{{ .GIT_ROOT }}/out/ansible-{{ .PROJECT }}-{{ .VERSION }}.tgz'
    cmds:
      - rm -f {{ .GIT_ROOT }}/out/ansible-{{ .PROJECT }}-*.tgz
      - npm version {{ .VERSION }} --no-git-tag-version
      - pnpm pack --pack-destination '{{ .GIT_ROOT }}/out'
      - defer: npm version 0.0.0 --no-git-tag-version
    silent: false
  clean:
    desc: Clean build artifacts
    dir: "{{ .TASKFILE_DIR }}"
    cmds:
      - rm -rf node_modules/.cache
version: "3"
