---
# see https://taskfile.dev/#/
version: "3"
env:
  # basically the same thing from .env file:
  # Avoid undesired extra hints from docker when pulling images
  DOCKER_CLI_HINTS: "false"
vars:
  VIRTUAL_ENV:
    sh: echo "${HOME}/.local/share/virtualenvs/vsa"
includes:
  base:
    taskfile: ../../Taskfile.base.yml
    internal: true
    flatten: true

tasks:
  default:
    dir: "{{ .TASKFILE_DIR }}"
    desc: Run most commands
    env:
      VERSION:
        sh: node -p "require('./package.json').version"
    cmds:
      - task: package
      - task: test
      - echo Done ansible-mcp-server {{.VERSION}}!
  build:
    dir: "{{ .TASKFILE_DIR }}"
    desc: Build the project
    deps:
      - setup
    cmds:
      - npm run compile
    generates:
      - out/server/**/*.*
    sources:
      - ../../vitest.config.ts
      - package-lock.json
      - package.json
      - src/**/*.*
      - test/**/*.*
      - tsconfig.json
      - exclude: "**/*-artifact-*.json"
  test:
    desc: Run all tests and coverage report
    deps:
      - build
    dir: "{{ .TASKFILE_DIR }}"
    generates:
      - ../../out/coverage/mcp/cobertura-coverage.xml # codecov.io
      - ../../out/coverage/mcp/coverage-final.json # IDE plugins
      - ../../out/coverage/mcp/lcov.info # sonar
      - ../../out/junit/mcp-test-results.xml
    sources:
      - ../../vitest.config.ts
      - package.json
      - src/**/*.*
      - test/**/*.*
      - tsconfig.json
      - exclude: "**/*-artifact-*.json"
    cmds:
      - npm run test
    interactive: true
  test-watch:
    desc: Run tests in watch mode
    dir: "{{ .TASKFILE_DIR }}"
    cmds:
      - npm run test:watch
    interactive: true
  package:
    desc: Package MCP server
    deps:
      - build
    dir: "{{ .TASKFILE_DIR }}"
    sources:
      - README.md
      - package*.json
      - src/**/*.*
      - tsconfig.json
    generates:
      - "../../out/@ansible-ansible-mcp-server*.tgz"
    cmds:
      - rm -f {{ .GIT_ROOT }}/out/@ansible-ansible-mcp-server*.tgz
      - yarn pack --out '{{ .GIT_ROOT }}/out/%s-%v.tgz'
    silent: false
  clean:
    desc: Clean build artifacts
    dir: "{{ .TASKFILE_DIR }}"
    cmds:
      - rm -rf out/server
      - rm -rf node_modules/.cache
