---
# See https://github.com/ansible/team-devtools/blob/main/.github/workflows/ack.yml
name: ack
on:
  merge_group:
  pull_request_target:
    types: [opened, labeled, unlabeled, reopened, edited]

jobs:
  ack:
    uses: ansible/team-devtools/.github/workflows/ack.yml@main
    secrets: inherit
