name: Code Coverage

on: [push, pull_request]

jobs:
  tests:
    name: Prepare
    runs-on: ubuntu-latest
    steps:
      - name: Yarn setup
        uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 20
      - uses: actions/checkout@v4
      - name: Install the dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Run unit-tests
        uses: borales/actions-yarn@v4
        with:
          cmd: unit-tests

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
